security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        darevish\DemoBundle\Entity\DemoUser: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        chain_provider:
            chain:
                providers: [in_memory, db_users]
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        db_users:
            entity: { class: darevishDemoBundle:DemoUser }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            provider: chain_provider
            anonymous: ~
            form_login:
                check_path: login_check
                login_path: login
            logout:
                path:   logout
                target: default_index

    access_control:
        - { path: ^/static/, roles: ROLE_USER }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
